code/__init__.py
__name__ == "src"

code/powertools/__init__.py
__all__ = ["main"]

code/powertools/main.py
import requests
import json
import yaml
import os
from bs4 import BeautifulSoup

# set URLS for APIs
proPublica_DataTable_url = (
    "https://api.propublica.org/congress/v1/bills/search.json?query={}&sort=date"
)
proPublica_bill_url = "https://api.propublica.org/congress/v1/116/bills/{}.json"

proPublica_SENATE_member_url = (
    "https://api.propublica.org/congress/v1/members/{}/{}/current.json"
)
proPublica_SENATE_member_id_url = (
    "https://api.propublica.org/congress/v1/members/{}.json"
)
proPublica_HOUSE_member_url = "https://api.propublica.org/congress/v1/members/{chamber}/{state}/{district}/current.json"

govtrack_bill_url = "https://www.govinfo.gov/link/bills/116/{}/{}?link-type=html"


def generate_datatable_JSON(api_key, topicQueryString):
    proPublica_DataTable_request_url = proPublica_DataTable_url.format(topicQueryString)
    response = requests.get(
        proPublica_DataTable_request_url, headers={"X-API-KEY": api_key}
    )
    return response, json.dumps(response.json()["results"][0]["bills"])


def generate_bill_data(api_key, bill_slug):
    proPublica_bill_url_slug = proPublica_bill_url.format(bill_slug)
    response = requests.get(proPublica_bill_url_slug, headers={"X-API-KEY": api_key})
    return response, response.json()["results"]


def generate_bill_fulltext(api_key, bill_type, bill_number):
    govtrack_bill_url_formatted = govtrack_bill_url.format(bill_type, bill_number)
    response = requests.get(govtrack_bill_url_formatted)
    soup = BeautifulSoup(response.text, features="html.parser")

    soupTitle = soup.find("title")
    if soupTitle and "Service Error" in soupTitle.text:
        return "There was an error fetching the bill's full text. It could be this bill is too recent, or another error with GovTrack."

    return response, response.text


def get_contact_form_url(member_id):
    member_file = "{}.yaml".format(member_id)
    yaml_file = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "yaml", member_file)
    )
    with open(yaml_file, "r") as stream:
        yaml_data = yaml.safe_load(stream)

    return yaml_data["contact_form"]["steps"][0]["visit"]


def get_members_by_state(api_key, member_state):
    senate_members_formatted_url = proPublica_SENATE_member_url.format(
        "senate", member_state
    )
    response = requests.get(
        senate_members_formatted_url, headers={"X-API-KEY": api_key}
    )
    response_with_contact = []
    for i in response.json()["results"]:
        member_id = i["id"]
        contact_url = get_contact_form_url(member_id)
        i["contact_url"] = contact_url
        response_with_contact.append(i)
    return response, response_with_contact


def get_member_by_id(api_key, member_id):
    senate_member_by_id_url = proPublica_SENATE_member_id_url.format(member_id)
    response = requests.get(senate_member_by_id_url, headers={"X-API-KEY": api_key})
    response_with_contact = []
    for i in response.json()["results"]:
        member_id = i["id"]
        contact_url = get_contact_form_url(member_id)
        i["contact_url"] = contact_url
        response_with_contact.append(i)
    return response, response_with_contact

code/views/about.py
from flask import (
    Blueprint,
    render_template,
)

about_bp = Blueprint("about", __name__, url_prefix="/about")


@about_bp.route("/", methods=["GET", "POST"])
def show_about():
    return render_template("about.html")

code/views/bills.py
import json
from powertools.main import (
    generate_bill_data,
    generate_bill_fulltext,
    get_members_by_state,
    get_member_by_id,
)
from flask import (
    Blueprint,
    render_template,
    current_app,
)

bill = Blueprint("bill", __name__, url_prefix="/bill")


@bill.route("/<bill_id>", methods=["GET", "POST"])
def show_bill(bill_id):
    # set up api keys
    propublica_api_key = current_app.config["PROPUBLICA_API_KEY"]
    govtrack_api_key = current_app.config["GOVTRACK_API_KEY"]

    bill_data = generate_bill_data(propublica_api_key, bill_id)[1]
    bill_type = bill_data[0]["bill_type"]
    bill_number = bill_data[0]["number"].split(".")[-1]
    bill_fulltext = generate_bill_fulltext(govtrack_api_key, bill_type, bill_number)

    bill_title = bill_data[0]["short_title"]
    bill_intro_date = bill_data[0]["introduced_date"]
    bill_history = bill_data[0]["actions"]
    bill_sponsor_data = get_member_by_id(propublica_api_key, bill_data[0]["sponsor_id"])
    bill_sponsor_twitter = bill_sponsor_data[0]["twitter_account"]
    bill_sponsor_contact_url = bill_sponsor_data[0]["contact_url"]
    bill_sponsor_json = json.dumps(
        [
            {
                "sponsor_id": bill_data[0]["sponsor_id"],
                "sponsor": bill_data[0]["sponsor"],
                "sponsor_party": bill_data[0]["sponsor_party"],
                "sponsor_state": bill_data[0]["sponsor_state"],
                "sponsor_uri": bill_data[0]["sponsor_uri"],
                "sponsor_twitter": bill_sponsor_twitter,
                "sponsor_contact_url": bill_sponsor_contact_url,
            }
        ]
    )

    return render_template(
        "bills.html",
        bill_title=bill_title,
        bill_intro_date=bill_intro_date,
        bill_history=bill_history,
        bill_fulltext=bill_fulltext,
        bill_sponsor=bill_sponsor_json,
    )


@bill.route("/<bill_id>/history", methods=["GET", "POST"])
def get_bill_history(bill_id):
    api_key = current_app.config["PROPUBLICA_API_KEY"]
    bill_data = generate_bill_data(api_key, bill_id)[1]
    bill_history = bill_data[0]["actions"]
    return json.dumps(bill_history)


@bill.route("/members/all/<state_id>", methods=["GET", "POST"])
def get_all_members(state_id):
    api_key = current_app.config["PROPUBLICA_API_KEY"]
    all_members = get_members_by_state(api_key, state_id)[1]
    return json.dumps(all_members)

code/views/landing.py
from flask import (
    Blueprint,
    render_template,
)

landing = Blueprint("landing", __name__, url_prefix="/")


@landing.route("/", methods=["GET", "POST"])
def hello():
    return render_template("home.html")

code/views/search.py
from powertools.main import generate_datatable_JSON

from flask import (
    Blueprint,
    render_template,
    current_app,
)

search = Blueprint("search", __name__, url_prefix="/search")


@search.route("/", methods=["GET", "POST"])
def show_search():
    return render_template("search.html")


@search.route("/t/<topicQueryString>", methods=["GET", "POST"])
def generate_JSON(topicQueryString):
    propublica_api_key = current_app.config["PROPUBLICA_API_KEY"]
    DataTable_data = generate_datatable_JSON(propublica_api_key, topicQueryString)
    return DataTable_data

code/templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='about-style.css') }}">
<div id="main-about-container">
  <h2>THE IDEA</h2>
  <div class="container">
    <p>The idea for Track The Change started with the recognition that our ability to effectively communicate with our legislative
      leaders is being frustrated by the transformations brought on by the digital age. </p><p>There are so many channels, platforms and
      social media services that many of us find it difficult to swim through the sea of usernames in an effort to be heard. Track The Change
      has a simple goal: <b>provide a unified service that synthesizes the disparate contact information and methods for Congress men
      and women.</b> As a little bonus, I've also added a basic bill searching tool that will show you recently drafted legislation so you
      can contact your representatives about something substantive should you feel inclined to do so.
  </p>
  <div class="container-the-data">
      <h2>THE DATA</h2>
      <p>Most of the legislative data such as bill numbers, bill text and history is sourced from <a href="https://projects.propublica.org/api-docs/congress-api/">ProPublica's Congress API</a>.</p>
      <p>The full text of a bill, when available, is retrieved from <a href="https://www.govinfo.gov/app/collection/bills">GovTrack's bill repository</a>.  </p>
      <p>Contact information for legislators is sourced in large part with help from the <a href="https://theunitedstates.io/contact-congress/">Contact Congress</a> project.
  </div>
  <div class="container-versions">
      <h2>VERSIONS</h2>
      <p id="initial-release" data-date="June 2020">Initial release</p>
      <p data-date="Fall 2020">Add support for House members and add support for preformatted contact forms </p>
  </div>

</div>

{% endblock %}

code/templates/base.html
<!doctype html>
<meta name="viewport" content="viewport-fit=cover">
<title>{% block title %}{% endblock %} - Track The Change</title>

<!-- custom JS/CSS -->
<link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">

<!-- fonts -->
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&display=swap" rel="stylesheet">

<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.js"></script>

<!-- selectize -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.css">

<!-- DataTables -->
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">

<nav>
  <h1>Track The Change</h1>
  <ul>
    <li><a href="{{ url_for('landing.hello')}}">home</a>
    <li><a href="{{ url_for('search.show_search') }}">search</a>
    <li><a href="{{ url_for('about.show_about') }}">about</a>
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block content %}{% endblock %}
</section>

code/templates/bills.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bill-style.css') }}">
<hr>
<div id='banner-top-title-container'>
  <span class='bill-title'>{{ bill_title }}</span>
  <span class='bill-intro-date'>Introduced: {{ bill_intro_date }}</span>
</div>
<div id='parent-body-container'>
  <div id='sidepanel-nav-bar-container'>
    <span id='bill-text-tab' class='bill-sidepanel-tab active'>Bill text</span>
    <span href="#" id='bill-history-tab' class='bill-sidepanel-tab'>Bill history</span>
    <span href="#" id='bill-sponsors-tab' class='bill-sidepanel-tab'>Sponsor(s)</span>
    <span href="#" id='bill-contact-tab' class='bill-sidepanel-tab'>Contact</span>
  </div>
  <div id='bill-data-container'>
    <div id='bill-text-pane' class='bill-data-pane'>
      <div>
        {% if 'another error with GovTrack' in bill_fulltext %}
          <p style="margin-left:15%;color:red">{{ bill_fulltext|safe }}</p>
        {% else %}
          {{ bill_fulltext|safe }}
        {% endif %}
      </div>
    </div>
    <div id='bill-history-pane' class='bill-data-pane'>
        <div id="timeline-content">
          <p id='bill-history-title'>Bill History</p>
            <ul class="timeline">
            </ul>
          </div>
    </div>
    <div id="bill-sponsors-container">
      <div id='bill-sponsors-pane' class='bill-data-pane'>
        <p id='sponsors-title'>Sponsors</p>
        <div id='sponsors-contact-pane'>
          <div class='sponsor-row'>
          </div>
        </div>
      </div>
    </div>
    <div id='bill-contact-pane' class='bill-data-pane'>
      <div id='state-select-container'>
        <select id="state-select">
          <option value="" disabled selected>Pick a state</option>
        	<option value="AL">Alabama</option>
        	<option value="AK">Alaska</option>
        	<option value="AZ">Arizona</option>
        	<option value="AR">Arkansas</option>
        	<option value="CA">California</option>
        	<option value="CO">Colorado</option>
        	<option value="CT">Connecticut</option>
        	<option value="DE">Delaware</option>
        	<option value="DC">District Of Columbia</option>
        	<option value="FL">Florida</option>
        	<option value="GA">Georgia</option>
        	<option value="HI">Hawaii</option>
        	<option value="ID">Idaho</option>
        	<option value="IL">Illinois</option>
        	<option value="IN">Indiana</option>
        	<option value="IA">Iowa</option>
        	<option value="KS">Kansas</option>
        	<option value="KY">Kentucky</option>
        	<option value="LA">Louisiana</option>
        	<option value="ME">Maine</option>
        	<option value="MD">Maryland</option>
        	<option value="MA">Massachusetts</option>
        	<option value="MI">Michigan</option>
        	<option value="MN">Minnesota</option>
        	<option value="MS">Mississippi</option>
        	<option value="MO">Missouri</option>
        	<option value="MT">Montana</option>
        	<option value="NE">Nebraska</option>
        	<option value="NV">Nevada</option>
        	<option value="NH">New Hampshire</option>
        	<option value="NJ">New Jersey</option>
        	<option value="NM">New Mexico</option>
        	<option value="NY">New York</option>
        	<option value="NC">North Carolina</option>
        	<option value="ND">North Dakota</option>
        	<option value="OH">Ohio</option>
        	<option value="OK">Oklahoma</option>
        	<option value="OR">Oregon</option>
        	<option value="PA">Pennsylvania</option>
        	<option value="RI">Rhode Island</option>
        	<option value="SC">South Carolina</option>
        	<option value="SD">South Dakota</option>
        	<option value="TN">Tennessee</option>
        	<option value="TX">Texas</option>
        	<option value="UT">Utah</option>
        	<option value="VT">Vermont</option>
        	<option value="VA">Virginia</option>
        	<option value="WA">Washington</option>
        	<option value="WV">West Virginia</option>
        	<option value="WI">Wisconsin</option>
        	<option value="WY">Wyoming</option>
        </select>
      </div>
      <div id="senator-contact-container">
        <p id='senator-title'>Senators</p>
        <div id='senator-contact-pane'>
          <div class='senator-row'>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript"> var billHistory = {{ bill_history|tojson|safe }}</script>
<script type="text/javascript"> var billSponsor = {{ bill_sponsor|safe }}</script>
<script type="text/javascript" src="{{ url_for('static', filename='bills.js') }}" defer></script>
<script type="text/javascript">
  var twitterIconUrl = "{{ url_for('static', filename='twitter.png')}}"
  var writeIconUrl = "{{ url_for('static', filename='write.png')}}"
</script>


{% endblock %}

code/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='home-style.css') }}">
<div id="main-home-container">
  <div id="isbell-quote-container">
    <p><b>"There's no such thing as someone else's war."</b></p>
    <p><i>Jason Isbell</i></p>
  </div>
  <div id='main-home-container'>
    
  </div>


</div>

{% endblock %}

code/templates/search.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='search-style.css') }}">
<script type="text/javascript" src="{{ url_for('static', filename='search.js') }}"></script>
<div id='home-sidepanel' class='sidepanel'>
  <label for="topic-select">policy categories</label>
  <input type="text" id="topic-select">
</div>
<div id='main-datatable-container' class='container'>
  <table id="test-table">
    <thead>
      <tr>
          <th>Policy tags</th>
          <th>Introduced</th>
          <th>Bill Number</th>
          <th>Bill Name</th>
          <th></th>
      </tr>
    </thead>
  </table>
</div>
{% endblock %}